### PR TITLE
Delegate more control to templates

### PR DESCRIPTION
**Pull request by solidgoldbomb**
The previous implementation of make_routes was built with an assumption
that exactly one exabgp API command would be rendered based on any list
of cidrs.  This assumption makes sense for blocking via null routes + RPF
to cover blocking in forward and reverse directions.

The single-route-per-block assumption does not hold, however, for
scenarios where the blocking is accomplished via BGP flowspec routes.  In
this case, two exabgp route announcements per cidr would need to be added.
One for forward traffic and the other for reverse traffic flows.
Something like this for each cidr:
  * announce flow source      198.51.100.0/24 extended-community rate-limit:0
  * announce flow destination 198.51.100.0/24 extended-community rate-limit:0

This level of control requires that the template is able to loop over the
cidrs as well as render the action (announce/withdraw) for each line as
appropriate.

This change gives the template full control by allowing the template to
render the action as well as to receive the cidrs as a list rather than a
space-separated string.

Note: This change changes the API to the template so it will cause some (simple to fix) breakage for any users who already have a custom template.

### CODE REVIEW

**Comment by solidgoldbomb** [comment]
There are probably many ways to accomplish this.  Just let me know if you prefer a different way and I can try to adapt.

As a side-comment, I was doing some testing against ExaBGP 4.0.8 and I noticed that the 'announce attribute...' form (from the default template) no longer works against that version.  After some discussion on IRC/gitter, that seems to be an unintentional bug in 4.x/master.  Issue is here in case you're interested: https://github.com/Exa-Networks/exabgp/issues/856.  Might be important for any users testing BHR with ExaBGP 4.x.  Also note that the config file format for 4.x has changed quite a bit too.

**Comment by JustinAzoff** [comment]
Looks good to me.. It makes a lot more sense like that.

I haven't tested 4.x at all myself, at least the last time I set it up 3.4 was still the recommended version.

**Comment by solidgoldbomb** [comment]
Thanks for merging.

**Comment by thomas-mangin** [comment]
The backward compatibility with 3.4 was restored on master today.

**Pull request merged**
